#!/usr/bin/env bash

RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() {
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo -e "${CYAN}info:${NC} $timestamp $1"
}

log_error() {
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo -e "${RED}error:${NC} $timestamp $1"
}
