#!/usr/bin/env bash
set -e
export DOTCLI_WORKDIR=$(cd $(dirname $0) && pwd)
# shellcheck source=common
. "$DOTCLI_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name

Version: $(cat $DOTCLI_WORKDIR/version)
https://github.com/aki21j/dotfiles/dotcli

Usage: $cli_name [command]

Commands:
  ls-themes    List all available zsh themes
  *            Help
"
  exit 1
}

# cli_log "Exporting config ..."
# [ ! -f "$DOTCLI_WORKDIR/config" ] \
#   && echo "ERROR: No $DOTCLI_WORKDIR/config file found. " \
#   && echo "cp $DOTCLI_WORKDIR/config.template $DOTCLI_WORKDIR/config and adjust." \
#   && exit 1

# export $(cat "$DOTCLI_WORKDIR/config" | xargs)

case "$1" in
  ls-themes|d)
    "$DOTCLI_WORKDIR/commands/list-themes" | tee -ia "$DOTCLI_WORKDIR/logs/list-themes.log"
    ;;
  *)
    cli_help
    ;;
esac
