#!/usr/bin/env bash
set -e
export CLI_WORKDIR=$(cd $(dirname $0) && pwd)
# shellcheck source=common
. "$CLI_WORKDIR/common"

help() {
  cli_name=${0##*/}
  echo "
$cli_name

Version: $(cat $CLI_WORKDIR/version)
https://github.com/aki21j/See-Al-I

Usage: $cli_name [command]

command   arg           description
  setup                 Setup see-al-i with basic dependencies.

  zsh     install       Install zsh on your pc
          ls-themes     List all available zsh themes
          set-theme     Set a theme from the list of available themes

  git     ls            List all available git configs
          use           Use one of the available configs.
  
  *                     Help
"
  exit 1
}

# log_info "Exporting config ..."
# [ ! -f "$CLI_WORKDIR/config" ] \
#   && echo "ERROR: No $CLI_WORKDIR/config file found. " \
#   && echo "cp $CLI_WORKDIR/config.template $CLI_WORKDIR/config and adjust." \
#   && exit 1

# export $(cat "$CLI_WORKDIR/config" | xargs)

case "$1" in
  setup|d)
    "$CLI_WORKDIR/commands/setup" "$1" | tee -ia "$CLI_WORKDIR/logs/app.log"
    ;;
  zsh|d)
    "$CLI_WORKDIR/commands/zsh" "$2" "$3" | tee -ia "$CLI_WORKDIR/logs/zsh.log"
    ;;
  git|d)
    "$CLI_WORKDIR/commands/git-config" "$2" "$3" | tee -ia "$CLI_WORKDIR/logs/app.log"
    ;;
  *)
    help
    ;;
esac
