#!/usr/bin/env bash
. "$CLI_WORKDIR/common"

help_setup() {
  echo "
command   arg           description
  setup                 Setup see-al-i with basic dependencies."
  exit 1
}

[ ! -n "$1" ] && help_setup

# add reqd packages here, separated by space
reqd_packages=(jq)

setup_env(){
  for p in "${reqd_packages[@]}"
  do
    install_package $p
  done
}

install_package(){
  REQUIRED_PKG="${1}"
  PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG | grep "install ok installed")
  log_info "Checking for $REQUIRED_PKG: $PKG_OK"
  if [ "" = "$PKG_OK" ]; then
    log_info "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
    sudo apt-get --yes install $REQUIRED_PKG 
  fi
}


case "$1" in
  setup|d)
    setup_env
    ;;
  *)
    setup_env
    ;;
esac

log_info "Fin..."
