#!/usr/bin/env bash
set -e
. "$CLI_WORKDIR/common"

help_zsh() {
  echo "
command   arg           description
  zsh     install       Install zsh on your pc
          ls-themes     List all available zsh themes
          set-theme     Set a theme from the list of available themes

Usage: 
  zsh install
  zsh ls-themes
  zsh set-theme <THEME_NAME>"
  exit 1
}

[ ! -n "$1" ] && help_zsh

themes_list=()

install_zsh(){
  default_shell=${SHELL##*/}

  if [[ "${default_shell}" =~ "zsh" ]]; then
      log_info "zsh is already set as your default shell."
  fi
  if [[ ! "${default_shell}" =~ "zsh" ]]; then
      log_info "Installing zsh..."
      # install zsh
      sudo apt install zsh
      # download and install oh-my-zsh for themes and fonts
      sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
      # make zsh the default
      chsh -s $(which zsh)
      echo "Log out and login again for the changes to take place."
  fi
}

get_themes(){
  zsh_themes_dir=$ZSH/themes
  log_info "oh-my-zsh directory: $ZSH"

  files=($zsh_themes_dir/*)
  pos=$(( ${#files[*]} - 1 ))
  last=${files[$pos]}

  for entry in "$zsh_themes_dir"/*
  do
    theme_with_ext=${entry##*/}
    theme=$(echo "$theme_with_ext" | cut -f 1 -d '.')
    
    if [[ $entry == $last ]]
    then
      themes_list+=("$theme")
      break
    else
      themes_list+=("$theme,")
    fi
  done
}

# function to list all available oh-my-zsh themes
list_themes(){
  get_themes
  log_info "available oh-my-zsh themes: "
  echo "${themes_list[@]}"
}


set_theme(){
  get_themes

  if [[ ! "${themes_list[@]}" =~ "${1}" ]]; then
      # throw error if user choice is not available
      log_error "$1 is not a valid theme"
  fi

  if [[ "${themes_list[@]}" =~ "${1}" ]]; then
      zshrc_path=$HOME/.zshrc
      update_command=s/^ZSH_THEME=.*/ZSH_THEME="${1}"/
      log_info "Updating zsh theme to: $1"
      sed -i "$update_command" $zshrc_path
      log_info "Run: source \$HOME/.zshrc or reload your terminal for the changes to take effect."
  fi

}

case "$1" in
  install|d)
    install_zsh
    ;;
  ls-themes|d)
    list_themes
    ;;
  set-theme|d)
    [ ! -n "$2" ] && help_zsh
    set_theme "$2"
    ;;
  *)
    help_zsh
    ;;
esac

log_info "Fin..."
